### ISSUE TITLE
Question: How to change background color of menubar of drawio app

### ISSUE THREAD

**Issue by liaham** [mikitex70/redmine_drawio#129]
Hi @mikitex70,

Today I have a question for you.

Do you know whether it is possible to change the blue background color of the menubar and some buttons in the drawio integration?

I cannot do this via CSS due to the iframe embedding.  Is it possible via Javascript or the like?

![grafik](https://github.com/mikitex70/redmine_drawio/assets/43378236/34de88ad-2214-4201-a1a1-fa19fe537899)

![grafik](https://github.com/mikitex70/redmine_drawio/assets/43378236/cad39ac8-92d1-4b34-8098-615592497ebf)

Thank you very much!

Best Regards
@liaham

**Comment by mikitex70** [comment]
Hi @liaham, let mi try but I think it is not possible: Redmine and Draw.io are different sites and so the browser is protecting/separating the two sites; the communication between Redmine and Draw.io is happening with messaging, which I think is a controlled mode to communicate and does allow only small interactions.

Perhaps the solution is to use a local Draw.io installation with modified styles. All can be automated: download the sources, patch and build the artifact (a container image for example). 
Or fork the repository Draw.io from GitHub, patch styles and build. This second solution is perhaps better because a simple `git fetch upstream` with a 'git rebase' allows you to download the latest updates while keeping your personal patches.

**Comment by liaham** [comment]
Hi @mikitex70,
Thank you for your quick response and ideas about how to change the styling. 

I thought you can influence it somehow because using drawio via app.diagrams.net or a desktop app does not have this blue menubar.
