### ISSUE TITLE
Duplicated diagram 

### ISSUE THREAD

**Issue by MathieuDuc35** [mikitex70/redmine_drawio#30]
I create a new diagram in a new issue, save it. Then I double click again for update it. Save the new diagram, refresh the page and I have 2 diagrams instead of one : 
![drawio](https://user-images.githubusercontent.com/25299314/27038201-9470534e-4f8a-11e7-8d71-2e84017646ac.png)

**Comment by mikitex70** [comment]
This is the expected behaviour if you are using the @drawio_attach@ macro: Redmine does not  have the API to update an attachment, not for deleting it (at least when I've started to implement the plugin), so the old version of diagram must be delete manually.
Also notice that every diagram name is saved with a suffix that is incremented after every save, so the attachment with the biggest suffix is the more recente.
Read the README.md, it is plenty of explanations.

**Comment by MathieuDuc35** [comment]
Ok thanks for your answer
