### ISSUE TITLE
drawing not included in pdf export

### ISSUE THREAD

**Issue by M0d3rn15t** [mikitex70/redmine_drawio#55]
Using the PDF export option for a Wiki page draw.io drawings are not rendered in the exported pdf file.

Info:
Editor: CKEditor

Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.3.6-p384 (2017-12-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.5
  redmine_checklists             3.1.10
  redmine_ckeditor               1.1.5
  redmine_cms                    1.1.0
  redmine_contacts               4.1.2
  redmine_contacts_helpdesk      3.0.9
  redmine_contacts_invoices      4.1.6
  redmine_crm_mailchimp          1.0.2
  redmine_dmsf                   1.6.0
  redmine_drawio                 0.8.1
  redmine_favorite_projects      2.0.3
  redmine_finance                2.1.3
  redmine_people                 1.3.2
  redmine_products               2.0.4
  redmine_questions              0.0.7
  redmine_zenedit                0.0.2
  redmineup_tags                 2.0.1

**Comment by mikitex70** [comment]
This issue cannot be fixed because:
* Redmine doesn't support exporting to PDF images with the so called *datas URIs*, used by drawio; I've managed to *monkey patch* Redmine to be able to export such kind of images but there are other issues
* the drawio app produces PNG images with an incorrect CRC for the embedded source diagram; they are displayed correctly but some software (such the PDF export) cannot handle them correctly
* SVG diagrams cannot be drawn by the PDF exporters; I can convert them to PNG but the conversion has some trouble with the texts (they disappear)

The solution maybe to call, during the PDF export, the drawio site, sending it the diagram source and requesting an PNG export. This maybe slow, and I'm not sure it's feasible.

I  will keep to try to find a solution. but it would take time.

**Comment by M0d3rn15t** [comment]
This issue dramatically reduces the utility of this otherwise brilliant plugin.

I could foresee my redmine site almost entirely replacing all other office applications, however, with out a way to render pdf documents with the diagrams enclosed we will need to generate the documents with office and Visio anyway.
