### ISSUE TITLE
Render Redmine commands and macroses in SVG

### ISSUE THREAD

**Issue by dinya** [mikitex70/redmine_drawio#58]
Dear @mikitex70 

Is it possible to render Redmine commands (like issue links ``#1``) and macroses in SVG diagrams how it works for other formatted text fields in Redmine (wiki, issues, comments, etc.)? 

I think "double click to edit" may be placed to diagram menu (above/below figure). Also this menu will allow other features (buttons) like "Export diagram" and so on. What do you think about that?

**Comment by mikitex70** [comment]
Hi @dinya, sorry for the long (very long) delay in responding to you. For a reason I don't understand, I missed this issue.
Sorry, but it is not possible to render Redmine macros inside Drawio diagrams: macros are rendered on the server side, diagrams on the client side (if they are in XML format).

The `double click to edit` comes from an old Drawio example integration, and I kept it so that the page layout is not changed in any way. Perhaps an explicit button would be better (helps accessibility), I need to study the implications.
The button to edit a diagram is there if you use the `xml` format (also known as `drawio` format). These types of diagrams are rendered completely client-side, and there is a toolbar to help you navigate the diagram and edit it. Perhaps this is what you need.
