### ISSUE TITLE
Duplicate footer after save charts (incompatible with redmine_wiki_extensions)

### ISSUE THREAD

**Issue by gengen1988** [mikitex70/redmine_drawio#60]
Hi Michele,

This plugin is very useful to me, thanks! 

However I find it may cause some trouble when use it with another plugin.

When I finish drawing and save it back, redmine_drawio plugin may duplicate the footer which is created by redmine_wiki_extensions

Like this:

![screenshot_20181024_193506](https://user-images.githubusercontent.com/1947568/47427772-eecff200-d7c3-11e8-9d41-7caf94a2f79c.png)

My environment:

- Redmine: 3.4.6
- Redmine Drawio plugin: 0.8.2
- Redmine Wiki Extensions plugin: 0.8.1

see: https://github.com/haru/redmine_wiki_extensions

**Comment by mikitex70** [comment]
I was able to reproduce the problem.
This affects only the `drawio_attach` macro, the `drawio_dmsf` should work fine.
The problem is cause by the `redmine_wiki_extension` that appends `{{fnlist}}` at the of the wiki page; when modifing the diagram, the `drawio_attach` plugin must update the wiki page and maybe there is something at the and, before the `{{fnlist}}` macro, so the `redmine_wiki_extension` will append a new macro call.
I will fix this bug, maybe I will release it tomorrow.
