### ISSUE TITLE
Redmine 4.0 compatibility

### ISSUE THREAD

**Issue by jmtemmos** [mikitex70/redmine_drawio#64]
If this excellent plugin is compatible with 4.0 ? 
This is the only thing that prevents me from upgrading right now....

**Comment by mikitex70** [comment]
Yes!
See #62.

**Comment by bruce-cheng** [comment]
> Yes!  See #62.
Hi, I am not sure if I could stop to link with DMSF as a temporary solution. This is due to DMSF has a compatible issue in my redmine 4.0.3, I install DMSF plugin successfully, but it will let redmine stop servicing, got the Error ID( Message from application: No such file to load -- mongo.rb (LoadError)...). still wait DMSF version 2.0.1.

Without DMSF, I can't save the diagrams.

Please advise me and thank you in advance.

**Comment by nanego** [comment]
Hi @mikitex70 
Could you please update the plugin page in Redmine.org and specify compatibility with Redmine 4?
https://www.redmine.org/plugins/redmine_drawio
Thanks

**Comment by mikitex70** [comment]
Done, now it specifies the compatibility with Redmine 4.
I still testing, but I've found some problem with the `redmine_dmsf` plugin: the version `2.0.0` of that plugin doesn't install, the `devel-2.0.1` branch works better but there is some trouble with the WebDAV interface, so I can't save the diagrams.
So, my plugin is working fine but it isn't fully usable until the `redmine_dmsf` plugin is fixed.

**Comment by mikitex70** [comment]
No more feedback, I assume the issue is resolved.
