### ISSUE TITLE
redmine_drawio conflicting with additionals 

### ISSUE THREAD

**Issue by rambowm** [mikitex70/redmine_drawio#68]
I have Redmine v4.0.2 standalone with Additionals plugin v2.0.19. When I install redmine_drawio v0.8.5 and restart redmine, I get a server error whenever I open an editor. The production.log indicates there seems to be a loop between 'heads_for_wiki_formatter' and 'heads_for_wiki_formatter_with_additionals':
~~~~
SystemStackError (stack level too deep):

plugins/redmine_drawio/lib/redmine_drawio/helpers/markdown_helper.rb:33:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:14:in `heads_for_wiki_formatter_with_additionals'
plugins/redmine_drawio/lib/redmine_drawio/helpers/markdown_helper.rb:33:in `heads_for_wiki_formatter'
plugins/redmine_drawio/lib/redmine_drawio/helpers/markdown_helper.rb:33:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:14:in `heads_for_wiki_formatter_with_additionals'
plugins/redmine_drawio/lib/redmine_drawio/helpers/markdown_helper.rb:33:in `heads_for_wiki_formatter'
plugins/redmine_drawio/lib/redmine_drawio/helpers/markdown_helper.rb:33:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:14:in `heads_for_wiki_formatter_with_additionals'
plugins/redmine_drawio/lib/redmine_drawio/helpers/markdown_helper.rb:33:in `heads_for_wiki_formatter'
plugins/redmine_drawio/lib/redmine_drawio/helpers/markdown_helper.rb:33:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:14:in `heads_for_wiki_formatter_with_additionals'
~~~~
This continues for about 12000 lines

**Comment by mikitex70** [comment]
This time the bug is not mine, but it is caused by the `additionals` plugin.
Test cases:
1. * Redmine 4.0.2
    * additionals 2.0.20
    Works fine
2. * Redmine 4.0.2
    * additionals 2.0.20
    * [redmine_wiki_extensions](https://github.com/haru/redmine_wiki_extensions) 0.9.0
   Error, stack overflow
3. * Redmine 4.0.2
    * redmine_drawio v0.8.5
    * redmine_wiki_extensions 0.9.0
    Works fine

The `additionals` plugin uses the `alias_method` that causes problems with Rails 5 (the version used by Redmine 4), and must be changed to use the `prepend` method and the `super` instruction.
See also additionals [bug #48](https://github.com/AlphaNodes/additionals/issues/48) and [bug #46](https://github.com/AlphaNodes/additionals/issues/46).
