### ISSUE TITLE
only shown in Wiki editor not issue note editor

### ISSUE THREAD

**Issue by tazus** [mikitex70/redmine_drawio#74]
after install, the function shown and working in Wiki editor ok, but not in issue's note editor nor other editing area. I used ckeditor.

What could be the problem? TIA
Wiki 
![image](https://user-images.githubusercontent.com/79111/74799422-6dcb3100-530b-11ea-8be3-32d97e0575ac.png)

issue noted
![image](https://user-images.githubusercontent.com/79111/74799483-95ba9480-530b-11ea-9e5b-66b6f1462059.png)

**Comment by mikitex70** [comment]
I need some more info to be able to reproduce your issue:
* Redmine version
* CKEditor plugin version
* any other installed plugin which may interfere with the editing
* browser you used (just to be sure that the problem is not browser specific)

Without the CKEditor plugin the buttons show fine in the note editing form, so it should work also with the CKEditor. Maybe I've missed something...

**Comment by mikitex70** [comment]
No more feedback, issue closed.
Feel free to reopen it if you think this is the case.
